openapi: 3.0.1
info:
  title: Covalent API
  version: ''
paths:
  /v1/{chain_id}/address/{wallet_address}/balances_v2/:
    get:
      description: >-
        [Full Endpoint
        Documentation](https://www.covalenthq.com/docs/api/#/0/Get%20token%20balances%20for%20address/USD/1)


        Given `chain_id` and wallet `address`, return current token balances
        along with their spot prices. This endpoint supports a variety of token
        standards like ERC20, ERC721 and ERC1155. As a special case, network
        native tokens like ETH on Ethereum are also returned even though it's
        not a token contract.
      operationId: BalancesService.getTokenBalances
      tags:
        - ClassABalances
      parameters:
        - name: chain_id
          in: path
          required: true
          schema:
            type: string
        - name: wallet_address
          in: path
          required: true
          schema:
            type: string
        - name: nft
          in: query
          description: >-
            Set to `true` to return ERC721 and ERC1155 assets. Defaults to
            `false`.
          required: false
          schema:
            type: boolean
        - name: no-nft-fetch
          in: query
          description: >
            Set to `true` to skip fetching NFT metadata, which can result in
            faster responses.  Defaults to `false` and only applies when
            `nft=true`.
          required: false
          schema:
            type: boolean
        - name: quote-currency
          in: query
          description: The requested fiat currency.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassABalanceResponseType'
      summary: Get token balances for address
      security: &ref_0
        - BasicAuth: []
  /v1/{chain_id}/address/{wallet_address}/portfolio_v2/:
    get:
      description: >-
        [Full Endpoint
        Documentation](https://www.covalenthq.com/docs/api/#/0/Get%20historical%20portfolio%20value%20over%20time/USD/1)


        Given `chain_id` and wallet `address`, return wallet value for the last
        30 days at 24 hour interval timestamps.
      operationId: BalancesService.getHistoricalPortfolioValue
      tags:
        - ClassABalances
      parameters:
        - name: chain_id
          in: path
          required: true
          schema:
            type: string
        - name: wallet_address
          in: path
          required: true
          schema:
            type: string
        - name: quote-currency
          in: query
          description: The requested fiat currency.
          required: false
          schema:
            type: string
        - name: days
          in: query
          description: >
            The range of the historical portfolio in days, defaults to 30 days
            (max days = 2000).
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassAHistoricalPortfolioResponse'
      summary: Get Historic Portfolio value over time
      security: *ref_0
  /v1/{chain_id}/tokens/{contract_address}/nft_token_ids/:
    get:
      description: >
        [Full Endpoint
        Documentation](https://www.covalenthq.com/docs/api/#/0/Get%20NFT%20transactions%20for%20contract/USD/1)


        Given `chain_id` and `contract_address`, return a list of all token IDs 
        for the NFT contract on the blockchain."
      operationId: NftService.getTokenIds
      tags:
        - ClassANft
      parameters:
        - name: chain_id
          in: path
          required: true
          schema:
            type: string
        - name: contract_address
          in: path
          required: true
          schema:
            type: string
        - name: page_number
          in: query
          description: The specific page to be returned.
          required: false
          schema:
            type: integer
        - name: page_size
          in: query
          description: The number of results per page.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClassATokenIdResponseType'
      summary: Get NFT Token IDs for contract
      security: *ref_0
  /v1/pricing/historical_by_address/{chain_id}/{quote_currency}/{contract_address}/nft_token_ids/:
    get:
      description: >
        [Full Endpoint
        Documentation](https://www.covalenthq.com/docs/api/#/0/Get%20NFT%20transactions%20for%20contract/USD/1)

        Given `chain_id` and `contract_address`, return a list of all token IDs 
        for the NFT contract on the blockchain."
      operationId: PricingService.getTokenIds
      tags:
        - Pricing
      parameters:
        - name: chain_id
          in: path
          required: true
          schema:
            type: string
        - name: quote_currency
          in: path
          required: true
          schema:
            type: string
        - name: contract_address
          in: path
          required: true
          schema:
            type: string
        - name: page_number
          in: query
          description: The specific page to be returned.
          required: false
          schema:
            type: integer
        - name: page_size
          in: query
          description: The number of results per page.
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenIdResponseType'
      summary: Get NFT Token IDs for contract
      security: *ref_0
components:
  schemas:
    ClassABalanceResponseType:
      type: object
      properties:
        address:
          type: string
          description: The requested wallet address.
        updated_at:
          type: string
          format: date-time
          description: The updated time in UTC.
        next_update_at:
          type: string
          format: date-time
          description: The next updated time in UTC.
        quote_currency:
          type: string
          description: The requested fiat currency.
        items:
          type: array
          items:
            $ref: '#/components/schemas/ClassAWalletBalanceItem'
      required:
        - address
        - updated_at
        - next_update_at
        - quote_currency
        - items
    ClassAWalletBalanceItem:
      type: object
      properties:
        contract_decimals:
          type: integer
          description: Smart contract decimals.
        contract_name:
          type: string
          description: Smart contract name.
        contract_ticker_symbol:
          type: string
          description: Smart contract ticker symbol.
        contract_address:
          type: string
          description: Smart contract address.
        supports_erc:
          type: array
          items:
            type: string
          description: |
            The standard interface(s) supported for this token, eg: `ERC-20`.
        logo_url:
          type: string
          description: Smart contract URL.
        last_transferred_at:
          type: string
          format: date-time
          description: Last transferred date for a wallet.
        native_token:
          type: boolean
          description: >
            Indicates if a token is the chain's native gas token, eg: ETH on
            Ethereum.
        type:
          type: string
          description: One of `cryptocurrency`, `stablecoin`, `nft` or `dust`.
        balance:
          type: integer
          description: >-
            The asset balance. Use `contract_decimals` to scale this balance for
            display purposes.
        balance_24h:
          type: integer
          description: The asset balance 24 hours ago.
        quote_rate:
          type: number
          format: double
          description: The current spot exchange rate in `quote-currency`.
        quote_rate_24h:
          type: number
          format: double
          description: The spot exchange rate in `quote-currency` as of 24 hours ago.
        quote:
          type: number
          format: double
          description: The current balance converted to fiat in `quote-currency`.
        quote_24h:
          type: number
          format: double
      required:
        - contract_decimals
        - contract_name
        - contract_ticker_symbol
        - contract_address
        - supports_erc
        - logo_url
        - last_transferred_at
        - native_token
        - type
        - balance
        - balance_24h
        - quote_rate
        - quote_rate_24h
        - quote
        - quote_24h
    ClassAINFTMetadata:
      type: array
      items: {}
      description: Array of NFTs that are held under this contract.
    ClassAHistoricalPortfolioResponse:
      type: object
      properties:
        address:
          type: string
          description: The requested wallet address.
        updated_at:
          type: string
          format: date-time
          description: The updated time in UTC.
        next_update_at:
          type: string
          format: date-time
          description: The next updated time in UTC.
        quote_currency:
          type: string
          description: The requested fiat currency.
        chain_id:
          type: integer
          description: The requested chain ID.
        items:
          type: array
          items: {}
          description: List of tokens in portfolio
        pagination:
          $ref: '#/components/schemas/AppliedPagination'
      required:
        - address
        - updated_at
        - next_update_at
        - quote_currency
        - chain_id
        - items
        - pagination
    ClassATokenIdResponse:
      type: object
      properties:
        contract_decimals:
          type: integer
          description: Smart contract decimals.
        contract_name:
          type: string
          description: Smart contract name.
        contract_ticker_symbol:
          type: string
          description: Smart contract ticker symbol.
        contract_address:
          type: string
          description: Smart contract address.
        supports_erc:
          type: array
          items:
            type: string
          description: |
            The standard interface(s) supported for this token, eg: `ERC-20`.
        logo_url:
          type: string
          description: Smart contract URL.
        token_id:
          type: integer
          description: The list of token ids under the contract address.
      required:
        - contract_decimals
        - contract_name
        - contract_ticker_symbol
        - contract_address
        - supports_erc
        - logo_url
        - token_id
    ClassATokenIdResponseType:
      type: object
      properties:
        updated_at:
          type: string
          format: date-time
          description: The updated time in UTC.
        items:
          type: array
          items:
            $ref: '#/components/schemas/ClassATokenIdResponse'
          description: List of tokens in portfolio
        pagination:
          $ref: '#/components/schemas/AppliedPagination'
      required:
        - updated_at
        - items
        - pagination
    AppliedPagination:
      type: object
      properties:
        has_more:
          type: boolean
          description: true if we can paginate to get more data.
        page_number:
          type: integer
          description: The specific page being returned.
        page_size:
          type: integer
          description: The number of results per page.
        total_count:
          type: integer
          description: Total number of entries.
      required:
        - has_more
        - page_number
        - page_size
        - total_count
    TokenIdResponse:
      type: object
      properties:
        contract_decimals:
          type: integer
          description: Smart contract decimals.
        contract_name:
          type: string
          description: Smart contract name.
        contract_ticker_symbol:
          type: string
          description: Smart contract ticker symbol.
        contract_address:
          type: string
          description: Smart contract address.
        supports_erc:
          type: array
          items:
            type: string
          description: |
            The standard interface(s) supported for this token, eg: `ERC-20`.
        logo_url:
          type: string
          description: Smart contract URL.
        token_id:
          type: integer
          description: The list of token ids under the contract address.
      required:
        - contract_decimals
        - contract_name
        - contract_ticker_symbol
        - contract_address
        - supports_erc
        - logo_url
        - token_id
    TokenIdResponseType:
      type: object
      properties:
        updated_at:
          type: string
          format: date-time
          description: The updated time in UTC.
        items:
          type: array
          items:
            $ref: '#/components/schemas/TokenIdResponse'
          description: List of tokens in portfolio
        pagination:
          $ref: '#/components/schemas/AppliedPagination'
      required:
        - updated_at
        - items
        - pagination
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
servers:
  - url: https://api.covalenthq.com
    description: Production
